<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
	<!--Asakura Faction
	Asakura Clan-->
	<xsl:template match="Hero[@id='lord_1_asakura']"/>
    <xsl:template match="Hero[@id='lord_1_asakura_1']"/>
	<xsl:template match="Hero[@id='lord_1_asakura_2']"/>
	<xsl:template match="Hero[@id='lord_1_asakura_3']"/>
	<!--Yamazaki Clan-->
	<xsl:template match="Hero[@id='lord_1_yamazaki']"/>
	<xsl:template match="Hero[@id='lord_1_yamazaki_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_yamazaki_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_yamazaki_3']"/>
	<xsl:template match="Hero[@id='lord_1_yamazaki_4']"/>
	<xsl:template match="Hero[@id='lord_1_yamazaki_5']"/>
	<xsl:template match="Hero[@id='lord_1_yamazaki_6']"/>
	<xsl:template match="Hero[@id='lord_1_yamazaki_7']"/>
	<!--Mizoe Clan-->
	<xsl:template match="Hero[@id='lord_1_mizoe']"/>
	<xsl:template match="Hero[@id='lord_1_mizoe_1']"/>
	<xsl:template match="Hero[@id='lord_1_mizoe_2']"/>
	<xsl:template match="Hero[@id='lord_1_mizoe_3']"/>
	<xsl:template match="Hero[@id='lord_1_mizoe_4']"/>
	<xsl:template match="Hero[@id='lord_1_mizoe_5']"/>
	<!--Maeba Clan-->
	<xsl:template match="Hero[@id='lord_1_maeba']"/>
	<xsl:template match="Hero[@id='lord_1_maeba_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_maeba_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_maeba_3']"/>
	<xsl:template match="Hero[@id='lord_1_maeba_4']"/>
	<xsl:template match="Hero[@id='lord_1_maeba_5']"/>
	<xsl:template match="Hero[@id='lord_1_maeba_6']"/>
	
	<!--Anekouji Faction
	Anekouji Clan-->
	<xsl:template match="Hero[@id='lord_1_anekouji']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_1']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_2']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_3']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_4']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_5']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_6']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_7']"/>
	<xsl:template match="Hero[@id='lord_1_anekouji_8']"/>
	<!--Miki Clan-->
	<xsl:template match="Hero[@id='lord_1_miki']"/>
	<xsl:template match="Hero[@id='lord_1_miki_1']"/>
	<xsl:template match="Hero[@id='lord_1_miki_2']"/>
	<xsl:template match="Hero[@id='lord_1_miki_3']"/>
	<!--Uchigashima Clan-->
	<xsl:template match="Hero[@id='lord_1_uchigashima']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_uchigashima_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_uchigashima_3']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_4']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_5']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_6']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_7']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_8']"/>
	<xsl:template match="Hero[@id='lord_1_uchigashima_9']"/>
	
	<!--Oda Faction
	Maeda Clan-->
	<xsl:template match="Hero[@id='lord_1_maeda']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_maeda_2']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_3']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_4']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_5']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_6']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_7']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_8']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_9']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_10']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_11']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_12']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_13']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_14']"/>
	<xsl:template match="Hero[@id='lord_1_maeda_15']"/>
	<!--Ikko-Ikki Faction
	Shimotsuma  Clan-->
	<xsl:template match="Hero[@id='lord_1_shimotsuma']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_1']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_2']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_3']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_4']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_5']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_6']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_7']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_8']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_9']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_10']"/>
	<xsl:template match="Hero[@id='lord_1_shimotsuma_11']"/>
	<!--Shichiri Clan-->
	<xsl:template match="Hero[@id='lord_1_shichiri']"/>
	<xsl:template match="Hero[@id='lord_1_shichiri_1']"/>
	<xsl:template match="Hero[@id='lord_1_shichiri_2']"/>
	<xsl:template match="Hero[@id='lord_1_shichiri_3']"/>
	
	<!--Hatakeyama Faction
	Noto-Hatakeyama Clan-->
	<xsl:template match="Hero[@id='lord_1_notohatakeyama']"/>
	<xsl:template match="Hero[@id='lord_1_notohatakeyama_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_notohatakeyama_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_notohatakeyama_3']"/>
	<xsl:template match="Hero[@id='lord_1_notohatakeyama_4']"/>
	<!--Cho Clan-->
	<xsl:template match="Hero[@id='lord_1_cho']"/>
	<xsl:template match="Hero[@id='lord_1_cho_1']"/>
	<xsl:template match="Hero[@id='lord_1_cho_2']"/>
	<xsl:template match="Hero[@id='lord_1_cho_3']"/>
	<xsl:template match="Hero[@id='lord_1_cho_4']"/>
	<!--Yusa Clan-->
	<xsl:template match="Hero[@id='lord_1_yusa']"/>
	<xsl:template match="Hero[@id='lord_1_yusa_1']"/>
	<xsl:template match="Hero[@id='lord_1_yusa_2']"/>
	<!--Nukui Clan-->
	<xsl:template match="Hero[@id='lord_1_nukui']"/>
	<xsl:template match="Hero[@id='lord_1_nukui_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_nukui_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_nukui_3']"/>
	<xsl:template match="Hero[@id='lord_1_nukui_4']"/>
	<xsl:template match="Hero[@id='lord_1_nukui_5']"/>
	
	<!--Akechi Clan-->
	<xsl:template match="Hero[@id='lord_1_akechi']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_1']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_2']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_3']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_4']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_5']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_6']"/>
	<xsl:template match="Hero[@id='lord_1_akechi_7']"/>
	<!--Niwa clan-->
	<xsl:template match="Hero[@id='lord_1_niwa']"/>
	<xsl:template match="Hero[@id='lord_1_niwa_1']"/>
	<xsl:template match="Hero[@id='lord_1_niwa_2']"/>
	<xsl:template match="Hero[@id='lord_1_niwa_3']"/>

	<!-- Bakufu
	Tokugawa Clan-->
	<xsl:template match="Hero[@id='lord_1_tokugawa']"/>
	<xsl:template match="Hero[@id='lord_1_tokugawa_1']"/>
	<xsl:template match="Hero[@id='lord_1_tokugawa_2']"/>
	<xsl:template match="Hero[@id='lord_1_tokugawa_3']"/>
	<xsl:template match="Hero[@id='lord_1_tokugawa_4']"/>
	<!--Honda Clan-->
	<xsl:template match="Hero[@id='lord_1_honda']"/>
	<xsl:template match="Hero[@id='lord_1_honda_1']"/>
	<xsl:template match="Hero[@id='lord_1_honda_2']"/>
	<xsl:template match="Hero[@id='lord_1_honda_3']"/>
	<xsl:template match="Hero[@id='lord_1_honda_4']"/>
	<xsl:template match="Hero[@id='lord_1_honda_5']"/>
	<xsl:template match="Hero[@id='lord_1_honda_6']"/>
	<xsl:template match="Hero[@id='lord_1_honda_7']"/>
	<xsl:template match="Hero[@id='lord_1_honda_8']"/>
	<xsl:template match="Hero[@id='lord_1_honda_9']"/>
	<xsl:template match="Hero[@id='lord_1_honda_10']"/>
	<xsl:template match="Hero[@id='lord_1_honda_11']"/>
	<!--Sakakibara Clan-->
	<xsl:template match="Hero[@id='lord_1_sakakibara']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sakakibara_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sakakibara_2']"/>
	<xsl:template match="Hero[@id='lord_1_sakakibara_3']"/>
	<!--Sakai Clan-->
	<xsl:template match="Hero[@id='lord_1_sakai']"/>
	<xsl:template match="Hero[@id='lord_1_sakai_1']"/>
	<xsl:template match="Hero[@id='lord_1_sakai_2']"/>
	<xsl:template match="Hero[@id='lord_1_sakai_3']"/>
	<xsl:template match="Hero[@id='lord_1_sakai_4']"/>
	<!--Ii Clan-->
	<xsl:template match="Hero[@id='lord_1_ii']"/>
	<xsl:template match="Hero[@id='dead_lord_1_ii_1']"/>
	<xsl:template match="Hero[@id='lord_1_ii_2']"/>
	<xsl:template match="Hero[@id='lord_1_ii_3']"/>
	<xsl:template match="Hero[@id='lord_1_ii_4']"/>
	<!--Okubo Clan-->
	<xsl:template match="Hero[@id='lord_1_okubo']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_1']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_2']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_3']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_4']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_5']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_6']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_7']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_8']"/>
	<xsl:template match="Hero[@id='lord_1_okubo_9']"/>
	<!--Yuki Matsudaira Clan-->
	<xsl:template match="Hero[@id='lord_1_hattori']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_hattori_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_hattori_3']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_4']"/>
	<xsl:template match="Hero[@id='dead_lord_1_hattori_5']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_6']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_7']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_8']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_9']"/>
	<xsl:template match="Hero[@id='lord_1_hattori_10']"/>
	<!--Hisamatsu Matsudaira Clan-->
	<xsl:template match="Hero[@id='lord_1_hisamitsu_matsudaira']"/>
	<!--Takamatsu Matsudaira Clan-->
	<xsl:template match="Hero[@id='lord_1_takamatsu_matsudaira']"/>
	<!--Mito Tokugawa Clan-->
	<xsl:template match="Hero[@id='dead_lord_1_mito']"/>
	<xsl:template match="Hero[@id='lord_1_mito']"/>
	<xsl:template match="Hero[@id='lord_2_mito']"/>
	<!--Ikeda clan-->
	<xsl:template match="Hero[@id='lord_1_ikeda']"/>
	<xsl:template match="Hero[@id='lord_1_ikeda_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_ikeda_2']"/>
	<!--can they be married to a dead guy? might need to remove-->
	<xsl:template match="Hero[@id='lord_1_ikeda_3']"/>
	<xsl:template match="Hero[@id='lord_1_ikeda_4']"/>
	<xsl:template match="Hero[@id='lord_1_ikeda_5']"/>
	<xsl:template match="Hero[@id='lord_1_ikeda_6']"/>
	<!--Uesugi Faction
	Uesugi Clan-->
	<xsl:template match="Hero[@id='lord_1_uesugi']"/>
	<xsl:template match="Hero[@id='dead_lord_1_uesugi_1']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_2']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_uesugi_4']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_6']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_5']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_7']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_8']"/>
	<xsl:template match="Hero[@id='lord_1_uesugi_9']"/>
	<!--Makino Clan-->
	<xsl:template match="Hero[@id='lord_1_irobe']"/>
	<xsl:template match="Hero[@id='lord_1_irobe_1']"/>
	<xsl:template match="Hero[@id='lord_1_irobe_2']"/>
	<xsl:template match="Hero[@id='lord_1_irobe_3']"/>
	<!--Nobunari Mikawa Clan-->
	<xsl:template match="Hero[@id='lord_1_kakizaki']"/>
	<xsl:template match="Hero[@id='lord_1_kakizaki_1']"/>
	<xsl:template match="Hero[@id='lord_1_kakizaki_2']"/>
	<xsl:template match="Hero[@id='lord_1_kakizaki_3']"/>
	<!--Naito Mikawa Clan-->
	<xsl:template match="Hero[@id='lord_1_naoe']"/>
	<xsl:template match="Hero[@id='lord_1_naoe_1']"/>
	<xsl:template match="Hero[@id='lord_1_naoe_2']"/>
	<!--Tendo Oda Clan-->
	<xsl:template match="Hero[@id='lord_2_shibata']"/>
	<xsl:template match="Hero[@id='lord_2_shibata_1']"/>
	<xsl:template match="Hero[@id='dead_lord_2_shibata_2']"/>
	<xsl:template match="Hero[@id='dead_lord_2_shibata_3']"/>
	<xsl:template match="Hero[@id='lord_2_shibata_4']"/>
	<xsl:template match="Hero[@id='lord_2_shibata_5']"/>
	<!--Mizuno Clan-->
	<xsl:template match="Hero[@id='lord_1_jinbo']"/>
	<xsl:template match="Hero[@id='lord_1_jinbo_1']"/>
	<xsl:template match="Hero[@id='lord_1_jinbo_2']"/>
	<xsl:template match="Hero[@id='lord_1_jinbo_3']"/>
	<xsl:template match="Hero[@id='lord_1_jinbo_4']"/>
	<xsl:template match="Hero[@id='lord_1_jinbo_5']"/>
	<!--Murakami Clan-->
	<xsl:template match="Hero[@id='lord_2_murakami']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_1']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_2']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_3']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_4']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_5']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_6']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_7']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_8']"/>
	<xsl:template match="Hero[@id='lord_2_murakami_9']"/>
	<!--Honma Clan-->
	<xsl:template match="Hero[@id='lord_1_honma']"/>
	<xsl:template match="Hero[@id='lord_1_honma_1']"/>
	<xsl:template match="Hero[@id='lord_1_honma_2']"/>
	<xsl:template match="Hero[@id='lord_1_honma_3']"/>
	<xsl:template match="Hero[@id='lord_1_honma_4']"/>
	<xsl:template match="Hero[@id='lord_1_honma_5']"/>

	<!--Shonai Faction
	Ishihara Clan-->
	<xsl:template match="Hero[@id='lord_1_honjo']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_1']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_2']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_3']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_4']"/>
	<!-- Sakai -->
	<xsl:template match="Hero[@id='lord_1_honjo_5']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_6']"/>
	<xsl:template match="Hero[@id='lord_1_honjo_7']"/>

	<!--Himeji Faction
	Sakai Clan-->
	<xsl:template match="Hero[@id='lord_1_takeda']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_takeda_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_takeda_3']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_4']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_5']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_6']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_7']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_8']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_9']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_12']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_13']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_10']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_11']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_14']"/>
	<xsl:template match="Hero[@id='lord_1_takeda_15']"/>
	<!--Baba Clan-->
	<xsl:template match="Hero[@id='lord_1_baba']"/>
	<xsl:template match="Hero[@id='lord_1_baba_1']"/>
	<xsl:template match="Hero[@id='lord_1_baba_2']"/>
	<xsl:template match="Hero[@id='lord_1_baba_3']"/>
	<xsl:template match="Hero[@id='lord_1_baba_4']"/>
	<xsl:template match="Hero[@id='lord_1_baba_5']"/>
	<xsl:template match="Hero[@id='lord_1_baba_6']"/>
	<xsl:template match="Hero[@id='lord_1_baba_7']"/>
	<!--Kiso Clan-->
	<xsl:template match="Hero[@id='lord_1_kiso']"/>
	<xsl:template match="Hero[@id='lord_1_kiso_1']"/>
	<xsl:template match="Hero[@id='lord_1_kiso_2']"/>
	<xsl:template match="Hero[@id='lord_1_kiso_3']"/>
	<xsl:template match="Hero[@id='lord_1_kiso_4']"/>
	<xsl:template match="Hero[@id='lord_1_kiso_5']"/>
	<!--Sanada Clan-->
	<xsl:template match="Hero[@id='lord_1_sanada']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_1']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_2']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_3']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_4']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_5']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_6']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_7']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_8']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_9']"/>
	<xsl:template match="Hero[@id='lord_1_sanada_10']"/>
	<!--Nishina Clan-->
	<xsl:template match="Hero[@id='lord_1_nishina']"/>
	<xsl:template match="Hero[@id='dead_lord_1_nishina_1']"/>
	<!--can they be married to a dead guy? might need to remove-->
	<xsl:template match="Hero[@id='lord_1_nishina_2']"/>
	<xsl:template match="Hero[@id='lord_1_nishina_3']"/>
	<xsl:template match="Hero[@id='lord_1_nishina_4']"/>
	<!--Oyamada Clan-->
	<xsl:template match="Hero[@id='lord_1_oyamada']"/>
	<xsl:template match="Hero[@id='lord_1_oyamada_1']"/>
	<xsl:template match="Hero[@id='lord_1_oyamada_2']"/>
	<xsl:template match="Hero[@id='lord_1_oyamada_3']"/>
	<!--Anayama Clan-->
	<xsl:template match="Hero[@id='lord_1_anayama']"/>
	<xsl:template match="Hero[@id='lord_1_anayama_1']"/>
	<!--Yamagata Clan-->
	<xsl:template match="Hero[@id='lord_1_yamagata']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_1']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_2']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_3']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_4']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_5']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_6']"/>
	<xsl:template match="Hero[@id='lord_1_yamagata_7']"/>
	<!--Kasuga Clan-->
	<xsl:template match="Hero[@id='lord_1_kasuga']"/>
	<xsl:template match="Hero[@id='lord_1_kasuga_1']"/>
	<xsl:template match="Hero[@id='lord_1_kasuga_2']"/>
	<xsl:template match="Hero[@id='lord_1_kasuga_3']"/>
	<xsl:template match="Hero[@id='lord_1_kasuga_4']"/>
	<xsl:template match="Hero[@id='lord_1_kasuga_5']"/>
	<!--Iwo-Matsuyama Faction
	Imabari Matsudaira Clan-->
	<xsl:template match="Hero[@id='lord_1_imagawa']"/>
	<xsl:template match="Hero[@id='lord_1_imagawa_1']"/>
	<xsl:template match="Hero[@id='lord_1_imagawa_2']"/>
	<!--Matsuyama Matsudaira Clan-->
	<xsl:template match="Hero[@id='lord_1_asahina']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_1']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_2']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_3']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_4']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_5']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_6']"/>
	<xsl:template match="Hero[@id='lord_1_asahina_7']"/>
	<!--Takayama Clan (Imabari Retainers)-->
	<xsl:template match="Hero[@id='lord_1_fuji']"/>
	<xsl:template match="Hero[@id='lord_1_fuji_1']"/>
	<xsl:template match="Hero[@id='lord_1_fuji_2']"/>
	<xsl:template match="Hero[@id='lord_1_fuji_3']"/>
	<xsl:template match="Hero[@id='lord_1_fuji_4']"/>
	<xsl:template match="Hero[@id='lord_1_fuji_5']"/>
	<!--Hijika Okudaira Clan (Matsuyama Retainers)-->
	<xsl:template match="Hero[@id='lord_1_okabe']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_okabe_2']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_3']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_4']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_5']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_6']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_7']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_8']"/>
	<xsl:template match="Hero[@id='lord_1_okabe_9']"/>
</xsl:stylesheet>