<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
	<!--Takeda Faction
	Obata Clan-->
	<xsl:template match="Hero[@id='lord_1_obata']"/>
    <xsl:template match="Hero[@id='lord_1_obata_1']"/>
	<xsl:template match="Hero[@id='lord_1_obata_2']"/>
	<xsl:template match="Hero[@id='lord_1_obata_3']"/>
	<xsl:template match="Hero[@id='lord_1_obata_4']"/>
    <xsl:template match="Hero[@id='lord_1_obata_5']"/>
	<xsl:template match="Hero[@id='lord_1_obata_6']"/>
	<xsl:template match="Hero[@id='lord_1_obata_7']"/>
	<xsl:template match="Hero[@id='lord_1_obata_8']"/>
	<xsl:template match="Hero[@id='lord_1_obata_9']"/>
	<xsl:template match="Hero[@id='lord_1_obata_10']"/>
	<xsl:template match="Hero[@id='lord_1_obata_11']"/>
	<!--Uesugi Faction-->
	<!--Yura Clan-->
	<xsl:template match="Hero[@id='lord_1_yura']"/>
	<xsl:template match="Hero[@id='lord_1_yura_1']"/>
	<xsl:template match="Hero[@id='lord_1_yura_2']"/>
	<xsl:template match="Hero[@id='lord_1_yura_3']"/>
	<xsl:template match="Hero[@id='lord_1_yura_4']"/>
	<xsl:template match="Hero[@id='lord_1_yura_5']"/>
	<xsl:template match="Hero[@id='lord_1_yura_6']"/>
	<!--Hojo Faction-->
	<!--Hojo Clan-->
	<xsl:template match="Hero[@id='lord_1_hojo']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_1']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_2']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_3']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_4']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_5']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_6']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_7']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_8']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_9']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_10']"/>
	<xsl:template match="Hero[@id='lord_1_hojo_11']"/>
	<!--Matsuda Clan-->
	<xsl:template match="Hero[@id='lord_1_matsuda']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_1']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_2']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_matsuda_4']"/>
	<xsl:template match="Hero[@id='dead_lord_1_matsuda_5']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_6']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_7']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_8']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_9']"/>
	<xsl:template match="Hero[@id='lord_1_matsuda_10']"/>
	<!--Toyama Clan-->
	<xsl:template match="Hero[@id='lord_1_toyama']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_toyama_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_toyama_3']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_4']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_5']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_6']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_7']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_8']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_9']"/>
	<xsl:template match="Hero[@id='lord_1_toyama_10']"/>
	<!--didoji Clan-->
	<xsl:template match="Hero[@id='lord_1_didoji']"/>
	<xsl:template match="Hero[@id='lord_1_didoji_1']"/>
	<xsl:template match="Hero[@id='lord_1_didoji_2']"/>
	<xsl:template match="Hero[@id='lord_1_didoji_3']"/>
	<!--narita Clan-->
	<xsl:template match="Hero[@id='lord_1_narita']"/>
	<xsl:template match="Hero[@id='lord_1_narita_1']"/>
	<xsl:template match="Hero[@id='lord_1_narita_2']"/>
	<xsl:template match="Hero[@id='lord_1_narita_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_narita_4']"/>
	<xsl:template match="Hero[@id='dead_lord_1_narita_5']"/>
	<xsl:template match="Hero[@id='lord_1_narita_6']"/>
	<xsl:template match="Hero[@id='lord_1_narita_7']"/>
	<xsl:template match="Hero[@id='lord_1_narita_8']"/>
	<xsl:template match="Hero[@id='lord_1_narita_9']"/>
	<xsl:template match="Hero[@id='lord_1_narita_10']"/>
	<xsl:template match="Hero[@id='lord_1_narita_11']"/>
	<xsl:template match="Hero[@id='lord_1_narita_12']"/>
	<!--chiba Clan-->
	<xsl:template match="Hero[@id='lord_1_chiba']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_chiba_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_chiba_3']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_4']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_5']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_6']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_7']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_8']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_9']"/>
	<xsl:template match="Hero[@id='lord_1_chiba_10']"/>
	<!--oda Clan-->
	<xsl:template match="Hero[@id='lord_2_oda']"/>
	<xsl:template match="Hero[@id='lord_2_oda_1']"/>
	<xsl:template match="Hero[@id='dead_lord_2_oda_2']"/>
	<xsl:template match="Hero[@id='dead_lord_2_oda_3']"/>
	<xsl:template match="Hero[@id='lord_2_oda_4']"/>
	<xsl:template match="Hero[@id='lord_2_oda_5']"/>
	<xsl:template match="Hero[@id='lord_2_oda_6']"/>
	<xsl:template match="Hero[@id='lord_2_oda_7']"/>
	<xsl:template match="Hero[@id='lord_2_oda_8']"/>
	<xsl:template match="Hero[@id='lord_2_oda_9']"/>
	<!--kogakubo Clan-->
	<xsl:template match="Hero[@id='lord_1_kogakubo']"/>
	<xsl:template match="Hero[@id='lord_1_kogakubo_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_kogakubo_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_kogakubo_3']"/>
	<xsl:template match="Hero[@id='lord_1_kogakubo_4']"/>
	<xsl:template match="Hero[@id='lord_1_kogakubo_5']"/>
	<xsl:template match="Hero[@id='lord_1_kogakubo_6']"/>
	<xsl:template match="Hero[@id='lord_1_kogakubo_7']"/>
	<!--sano Clan-->
	<xsl:template match="Hero[@id='lord_1_sano']"/>
	<xsl:template match="Hero[@id='lord_1_sano_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sano_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sano_3']"/>
	<xsl:template match="Hero[@id='lord_1_sano_4']"/>
	<xsl:template match="Hero[@id='lord_1_sano_5']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sano_6']"/>
	<xsl:template match="Hero[@id='lord_1_sano_7']"/>
	<xsl:template match="Hero[@id='lord_1_sano_8']"/>
	<!--yuki Clan-->
	<xsl:template match="Hero[@id='lord_1_yuki']"/>
	<xsl:template match="Hero[@id='lord_1_yuki_1']"/>
	<xsl:template match="Hero[@id='lord_1_yuki_2']"/>
	<xsl:template match="Hero[@id='lord_1_yuki_3']"/>
	<xsl:template match="Hero[@id='lord_1_yuki_4']"/>
	<!--Satomi Faction-->
	<!--Satomi Clan-->
	<xsl:template match="Hero[@id='lord_1_satomi']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_1']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_2']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_3']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_4']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_5']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_6']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_7']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_8']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_9']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_10']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_11']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_12']"/>
	<xsl:template match="Hero[@id='lord_1_satomi_13']"/>
	<!--masaki Clan-->
	<xsl:template match="Hero[@id='lord_1_masaki']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_1']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_2']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_3']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_4']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_5']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_6']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_7']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_8']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_9']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_10']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_11']"/>
	<xsl:template match="Hero[@id='lord_1_masaki_12']"/>
	<!--sakai Clan-->
	<xsl:template match="Hero[@id='lord_2_sakai']"/>
	<xsl:template match="Hero[@id='lord_2_sakai_1']"/>
	<xsl:template match="Hero[@id='lord_2_sakai_2']"/>
	<!--Utsunomiya Faction-->
	<!--Utsunomiya Clan-->
	<xsl:template match="Hero[@id='lord_1_utsunomiya']"/>
	<xsl:template match="Hero[@id='lord_1_utsunomiya_1']"/>
	<xsl:template match="Hero[@id='lord_1_utsunomiya_2']"/>
	<!--haga Clan-->
	<xsl:template match="Hero[@id='lord_1_haga']"/>
	<xsl:template match="Hero[@id='lord_1_haga_1']"/>
	<xsl:template match="Hero[@id='lord_1_haga_2']"/>
	<xsl:template match="Hero[@id='lord_1_haga_3']"/>
	<xsl:template match="Hero[@id='lord_1_haga_4']"/>
	<xsl:template match="Hero[@id='lord_1_haga_5']"/>
	<!--kasama Clan-->
	<xsl:template match="Hero[@id='lord_1_kasama']"/>
	<xsl:template match="Hero[@id='lord_1_kasama_1']"/>
	<xsl:template match="Hero[@id='lord_1_kasama_2']"/>
	<xsl:template match="Hero[@id='lord_1_kasama_3']"/>
	<xsl:template match="Hero[@id='lord_1_kasama_4']"/>
	<!-- Kobuta-han -->
	<!-- Satake Clan-->
	<xsl:template match="Hero[@id='lord_1_satake']"/>
	<xsl:template match="Hero[@id='lord_1_satake_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_satake_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_satake_3']"/>
	<xsl:template match="Hero[@id='lord_1_satake_4']"/>
	<xsl:template match="Hero[@id='lord_1_satake_5']"/>
	<xsl:template match="Hero[@id='lord_1_satake_6']"/>
	<xsl:template match="Hero[@id='lord_1_satake_7']"/>
	<xsl:template match="Hero[@id='lord_1_satake_8']"/>
	<!--Satake Hokke Clan-->
	<xsl:template match="Hero[@id='lord_1_edo']"/>
	<xsl:template match="Hero[@id='lord_1_edo_1']"/>
	<xsl:template match="Hero[@id='lord_1_edo_2']"/>
	<!--Tagaya Clan-->
	<xsl:template match="Hero[@id='lord_1_daijo']"/>
	<xsl:template match="Hero[@id='lord_1_daijo_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_daijo_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_daijo_3']"/>
	<xsl:template match="Hero[@id='lord_1_daijo_4']"/>
	<xsl:template match="Hero[@id='lord_1_daijo_5']"/>
	<!-- Satake Minami Clan-->
	<xsl:template match="Hero[@id='lord_1_kashima']"/>
	<xsl:template match="Hero[@id='dead_lord_1_kashima_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_kashima_2']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_4']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_3']"/>
	<!-- Shibue -->
	<xsl:template match="Hero[@id='lord_1_kashima_5']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_6']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_7']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_8']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_9']"/>
	<xsl:template match="Hero[@id='lord_1_kashima_10']"/>
	<!--nasu Clan-->
	<xsl:template match="Hero[@id='lord_1_nasu']"/>
	<xsl:template match="Hero[@id='lord_1_nasu_1']"/>
	<xsl:template match="Hero[@id='lord_1_nasu_2']"/>
	<xsl:template match="Hero[@id='lord_1_nasu_3']"/>
</xsl:stylesheet>