<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
	<!--Ozu Faction-->
	<!--Kato Clan-->
	<xsl:template match="Hero[@id='lord_1_saionji']"/>
	<xsl:template match="Hero[@id='lord_1_saionji_1']"/>
	<xsl:template match="Hero[@id='lord_1_saionji_2']"/>
	<xsl:template match="Hero[@id='lord_1_saionji_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_saionji_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_saionji_2']"/>
	<!--Shintani Kato clan-->
	<xsl:template match="Hero[@id='lord_1_kashuji']"/>
	<xsl:template match="Hero[@id='lord_1_kashuji_1']"/>
	<xsl:template match="Hero[@id='lord_1_kashuji_2']"/>
	<xsl:template match="Hero[@id='lord_1_kashuji_3']"/>
	<!--hoketsu clan TOKU-->
	<xsl:template match="Hero[@id='lord_1_hoketsu']"/>
	<xsl:template match="Hero[@id='lord_1_hoketsu_1']"/>
	<xsl:template match="Hero[@id='lord_1_hoketsu_2']"/>
	<xsl:template match="Hero[@id='lord_1_hoketsu_3']"/>
	<!--Uwajima kingdom-->
	<!--Date clan-->
	<xsl:template match="Hero[@id='lord_1_ichijo']"/>
	<xsl:template match="Hero[@id='lord_1_ichijo_1']"/>
	<xsl:template match="Hero[@id='lord_1_ichijo_2']"/>
	<xsl:template match="Hero[@id='lord_1_ichijo_3']"/>
	<xsl:template match="Hero[@id='lord_1_ichijo_4']"/>
	<xsl:template match="Hero[@id='lord_1_aki_3']"/>
	<!--Doi clan-->
	<xsl:template match="Hero[@id='lord_1_doi']"/>
	<xsl:template match="Hero[@id='lord_1_doi_1']"/>
	<xsl:template match="Hero[@id='lord_1_doi_2']"/>
	<!--Kojima clan-->
	<xsl:template match="Hero[@id='lord_1_aki']"/>
	<xsl:template match="Hero[@id='lord_1_aki_1']"/>
	<xsl:template match="Hero[@id='lord_1_aki_2']"/>
	<!--Yoshida Date clan-->
	<xsl:template match="Hero[@id='lord_1_tsuno']"/>
	<xsl:template match="Hero[@id='lord_1_tsuno_1']"/>
	<xsl:template match="Hero[@id='lord_1_tsuno_2']"/>
	<xsl:template match="Hero[@id='lord_1_tsuno_3']"/>
	<xsl:template match="Hero[@id='lord_1_doi_3']"/>
	<!--Tosa Faction-->
	<!--Chosokabe clan-->
	<xsl:template match="Hero[@id='lord_1_chosokabe']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_1']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_2']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_3']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_4']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_5']"/>
	<xsl:template match="Hero[@id='lord_1_chosokabe_6']"/>
	<!--Kosokabe clan-->
	<xsl:template match="Hero[@id='lord_1_kosokabe']"/>
	<xsl:template match="Hero[@id='lord_1_kosokabe_1']"/>
	<!--kira clan-->
	<xsl:template match="Hero[@id='lord_1_kira']"/>
	<xsl:template match="Hero[@id='lord_1_kira_1']"/>
	<xsl:template match="Hero[@id='lord_1_kira_2']"/>
	<xsl:template match="Hero[@id='lord_1_kira_3']"/>
	<xsl:template match="Hero[@id='lord_1_kira_4']"/>
	<!--Hisatake clan-->
	<xsl:template match="Hero[@id='lord_1_hisatake']"/>
	<xsl:template match="Hero[@id='lord_1_hisatake_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_hisatake_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_hisatake_3']"/>
	<xsl:template match="Hero[@id='lord_1_hisatake_4']"/>
	<xsl:template match="Hero[@id='lord_1_hisatake_5']"/>
	<!--Yoshida clan-->
	<xsl:template match="Hero[@id='lord_1_yoshida']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_yoshida_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_yoshida_3']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_4']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_5']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_6']"/>
	<xsl:template match="Hero[@id='dead_lord_1_yoshida_7']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_8']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_9']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_10']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_11']"/>
	<xsl:template match="Hero[@id='lord_1_yoshida_12']"/>
	<!--Fukudome clan-->
	<xsl:template match="Hero[@id='lord_1_fukudome']"/>
	<xsl:template match="Hero[@id='lord_1_fukudome_1']"/>
	<xsl:template match="Hero[@id='lord_1_fukudome_2']"/>
	<!-- Tokushima Kingdom -->
	<!-- Hachisuka Clan -->
	<xsl:template match="Hero[@id='lord_1_miyoshi']"/>
	<xsl:template match="Hero[@id='lord_1_miyoshi_1']"/>
	<xsl:template match="Hero[@id='lord_1_miyoshi_2']"/>
	<xsl:template match="Hero[@id='lord_1_miyoshi_3']"/>
	<xsl:template match="Hero[@id='lord_1_miyoshi_4']"/>
	<xsl:template match="Hero[@id='dead_lord_1_miyoshi_1']"/>
	<xsl:template match="Hero[@id='lord_1_miyoshi_5']"/>
	<!--sogo clan-->
	<xsl:template match="Hero[@id='lord_1_sogo']"/>
	<xsl:template match="Hero[@id='lord_1_sogo_1']"/>
	<xsl:template match="Hero[@id='lord_1_sogo_2']"/>
	<xsl:template match="Hero[@id='lord_1_sogo_3']"/>
	<xsl:template match="Hero[@id='lord_1_sogo_4']"/>
	<xsl:template match="Hero[@id='lord_1_sogo_5']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sogo_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_sogo_2']"/>
	<!--shingai clan-->
	<xsl:template match="Hero[@id='lord_1_shingai']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_1']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_2']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_3']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_4']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_5']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_6']"/>
	<xsl:template match="Hero[@id='lord_1_shingai_7']"/>
	<!--Inada clan-->
	<xsl:template match="Hero[@id='lord_1_onishi']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_1']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_2']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_3']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_4']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_5']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_6']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_7']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_8']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_9']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_10']"/>
	<xsl:template match="Hero[@id='lord_1_onishi_11']"/>
	<xsl:template match="Hero[@id='dead_lord_1_onishi_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_onishi_2']"/>
</xsl:stylesheet>