<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
	<!--Aizu Faction
	Matsudaira Clan-->	
	<xsl:template match="Hero[@id='lord_1_ashina']"/>
	<xsl:template match="Hero[@id='lord_1_ashina_1']"/>
	<xsl:template match="Hero[@id='lord_1_ashina_2']"/>
	<xsl:template match="Hero[@id='lord_1_ashina_3']"/>
	<xsl:template match="Hero[@id='lord_1_ashina_4']"/>
	<!--Saigo Clan-->
	<xsl:template match="Hero[@id='lord_1_inawashiro']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_1']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_2']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_3']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_4']"/>
	<xsl:template match="Hero[@id='lord_1_saigo_a_1']"/>
	<xsl:template match="Hero[@id='lord_1_saigo_a_2']"/>
	<xsl:template match="Hero[@id='lord_1_saigo_a_3']"/>
	<xsl:template match="Hero[@id='lord_1_saigo_a_4']"/>
	<!--Yamakawa Clan-->
	<xsl:template match="Hero[@id='lord_1_saze']"/>
	<xsl:template match="Hero[@id='lord_1_saze_1']"/>
	<xsl:template match="Hero[@id='lord_1_saze_2']"/>
	<xsl:template match="Hero[@id='lord_1_saze_3']"/>
	<xsl:template match="Hero[@id='lord_1_saze_4']"/>
	<xsl:template match="Hero[@id='lord_1_saze_5']"/>
	<xsl:template match="Hero[@id='lord_1_saze_6']"/>
	<!--Naito Clan-->
	<xsl:template match="Hero[@id='lord_1_matsumoto']"/>
	<xsl:template match="Hero[@id='lord_1_matsumoto_1']"/>
	<xsl:template match="Hero[@id='lord_1_matsumoto_2']"/>
	<!--Tanaka Clan-->
	<xsl:template match="Hero[@id='lord_1_nikaido']"/>
	<xsl:template match="Hero[@id='lord_1_nikaido_1']"/>
	<xsl:template match="Hero[@id='lord_1_nikaido_2']"/>
	<!--Ou Reppan Domei-->
	<!--Soma Clan-->
	<xsl:template match="Hero[@id='lord_1_soma']"/>
	<xsl:template match="Hero[@id='lord_1_soma_1']"/>
	<xsl:template match="Hero[@id='lord_1_soma_2']"/>
	<xsl:template match="Hero[@id='lord_1_soma_3']"/>
	<xsl:template match="Hero[@id='lord_1_soma_4']"/>
	<xsl:template match="Hero[@id='lord_1_soma_5']"/>
	<!--Nihonmatsu Clan-->
	<xsl:template match="Hero[@id='lord_1_nihonmatsu']"/>
	<xsl:template match="Hero[@id='lord_1_nihonmatsu_1']"/>
	<xsl:template match="Hero[@id='lord_1_nihonmatsu_2']"/>
	<xsl:template match="Hero[@id='lord_1_nihonmatsu_3']"/>
	<xsl:template match="Hero[@id='lord_1_nihonmatsu_4']"/>
	<!-- OTHER -->
	<!--Inawashiro Clan-->
	<xsl:template match="Hero[@id='lord_1_inawashiro']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_1']"/>
	<xsl:template match="Hero[@id='lord_1_inawashiro_2']"/>
	<!--Tamura Clan-->
	<xsl:template match="Hero[@id='lord_1_tamura']"/>
	<xsl:template match="Hero[@id='lord_1_tamura_1']"/>
	<xsl:template match="Hero[@id='lord_1_tamura_2']"/>
	<xsl:template match="Hero[@id='lord_1_tamura_3']"/>
	<xsl:template match="Hero[@id='lord_1_tamura_4']"/>
	<xsl:template match="Hero[@id='lord_1_tamura_5']"/>
	<!--Okada Clan-->
	<xsl:template match="Hero[@id='lord_1_okada']"/>
	<xsl:template match="Hero[@id='lord_1_okada_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_okada_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_okada_3']"/>
	<xsl:template match="Hero[@id='lord_1_okada_4']"/>
	<xsl:template match="Hero[@id='lord_1_okada_5']"/>
	<xsl:template match="Hero[@id='lord_1_okada_6']"/>
	<xsl:template match="Hero[@id='lord_1_okada_7']"/>
	<xsl:template match="Hero[@id='lord_1_okada_8']"/>
	<xsl:template match="Hero[@id='lord_1_okada_9']"/>
	<xsl:template match="Hero[@id='lord_1_okada_10']"/>
	<!--Sendai Faction-->
	<!--Date Clan-->
	<xsl:template match="Hero[@id='lord_1_date']"/>
	<xsl:template match="Hero[@id='lord_1_date_1']"/>
	<xsl:template match="Hero[@id='lord_1_date_2']"/>
	<xsl:template match="Hero[@id='lord_1_date_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_date_4']"/>
	<xsl:template match="Hero[@id='dead_lord_1_date_5']"/>
	<xsl:template match="Hero[@id='lord_1_date_6']"/>
	<xsl:template match="Hero[@id='lord_1_date_7']"/>
	<xsl:template match="Hero[@id='lord_1_date_8']"/>
	<xsl:template match="Hero[@id='lord_1_date_9']"/>
	<!--Katakura Clan-->
	<xsl:template match="Hero[@id='lord_1_katakura']"/>
	<xsl:template match="Hero[@id='dead_lord_1_katakura_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_katakura_2']"/>
	<xsl:template match="Hero[@id='lord_1_katakura_3']"/>
	<xsl:template match="Hero[@id='lord_1_katakura_4']"/>
	<!--Tamura Clan-->
	<xsl:template match="Hero[@id='lord_1_oniniwa']"/>
	<xsl:template match="Hero[@id='lord_1_oniniwa_1']"/>
	<xsl:template match="Hero[@id='lord_1_oniniwa_2']"/>
	<xsl:template match="Hero[@id='lord_1_oniniwa_3']"/>
	<xsl:template match="Hero[@id='lord_1_oniniwa_4']"/>
	<!--Watari/Wakuya Date Clan-->
	<xsl:template match="Hero[@id='lord_1_watari']"/>
	<xsl:template match="Hero[@id='lord_1_watari_1']"/>
	<xsl:template match="Hero[@id='lord_1_watari_2']"/>
	<xsl:template match="Hero[@id='lord_1_watari_3']"/>
	<!--Watari Date Clan-->
	<xsl:template match="Hero[@id='lord_1_osaki']"/>
	<xsl:template match="Hero[@id='lord_1_osaki_1']"/>
	<xsl:template match="Hero[@id='lord_1_osaki_2']"/>
	<xsl:template match="Hero[@id='lord_1_osaki_3']"/>
	<!--Tome Date Clan-->
	<xsl:template match="Hero[@id='lord_1_kasai']"/>
	<xsl:template match="Hero[@id='lord_1_kasai_1']"/>
	<xsl:template match="Hero[@id='lord_1_kasai_2']"/>
	<xsl:template match="Hero[@id='lord_1_kasai_3']"/>
	<!--Iwadeyama Date Clan-->
	<xsl:template match="Hero[@id='lord_1_iwaki']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_1']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_2']"/>
	<!--Rusu/Mizusawa Date Clan-->
	<xsl:template match="Hero[@id='lord_1_rusu']"/>
	<xsl:template match="Hero[@id='lord_1_rusu_1']"/>
	<xsl:template match="Hero[@id='lord_1_rusu_2']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_3']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_4']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_5']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_6']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_7']"/>
	<xsl:template match="Hero[@id='lord_1_iwaki_8']"/>
	<!-- Fukushima-han -->
	<!--Itakura Clan-->
	<xsl:template match="Hero[@id='lord_1_mogami']"/>
	<xsl:template match="Hero[@id='lord_1_mogami_1']"/>
	<xsl:template match="Hero[@id='lord_1_mogami_2']"/>
	<xsl:template match="Hero[@id='lord_1_mogami_3']"/>
	<xsl:template match="Hero[@id='lord_1_mogami_4']"/>
	<xsl:template match="Hero[@id='lord_1_mogami_5']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_6']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_7']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_8']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_9']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_10']"/>
	<xsl:template match="Hero[@id='lord_1_itakura_11']"/>
	<!--Tendo Clan-->
	<xsl:template match="Hero[@id='lord_1_tendo']"/>
	<xsl:template match="Hero[@id='lord_1_tendo_1']"/>
	<xsl:template match="Hero[@id='lord_1_tendo_2']"/>
	<xsl:template match="Hero[@id='lord_1_tendo_3']"/>
	<xsl:template match="Hero[@id='lord_1_tendo_4']"/>
	<!--Ujiie Clan-->
	<xsl:template match="Hero[@id='lord_1_ujiie']"/>
	<xsl:template match="Hero[@id='lord_1_ujiie_1']"/>
	<xsl:template match="Hero[@id='lord_1_ujiie_2']"/>
	<!--Nobesawa Clan-->
	<xsl:template match="Hero[@id='lord_1_nobesawa']"/>
	<xsl:template match="Hero[@id='lord_1_nobesawa_1']"/>
	<xsl:template match="Hero[@id='lord_1_nobesawa_2']"/>
	<!--Tateoka Clan-->
	<xsl:template match="Hero[@id='lord_1_tateoka']"/>
	<xsl:template match="Hero[@id='lord_1_tateoka_1']"/>
	<xsl:template match="Hero[@id='lord_1_tateoka_2']"/>
	<xsl:template match="Hero[@id='lord_1_tateoka_3']"/>
	<!--Shonai Faction-->
	<!--Sakai Clan-->
	<xsl:template match="Hero[@id='lord_1_daihoji']"/>
	<xsl:template match="Hero[@id='lord_1_daihoji_1']"/>
	<xsl:template match="Hero[@id='lord_1_daihoji_2']"/>
	<xsl:template match="Hero[@id='lord_1_daihoji_3']"/>
	<xsl:template match="Hero[@id='lord_1_daihoji_4']"/>
	<!--Sakai Okunosuke Clan-->
	<xsl:template match="Hero[@id='lord_1_onodera']"/>
	<xsl:template match="Hero[@id='lord_1_onodera_1']"/>
	<xsl:template match="Hero[@id='lord_1_onodera_2']"/>
	<xsl:template match="Hero[@id='lord_1_onodera_3']"/>
	<xsl:template match="Hero[@id='lord_1_onodera_4']"/>
	<!--Matsudaira Jinzaburo Clan-->
	<xsl:template match="Hero[@id='lord_1_sakenobe']"/>
	<xsl:template match="Hero[@id='lord_1_sakenobe_1']"/>
	<xsl:template match="Hero[@id='lord_1_sakenobe_2']"/>
	<!--Matsuyama Sakai Clan-->
	<xsl:template match="Hero[@id='lord_1_nikaho']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_1']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_2']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_3']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_4']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_5']"/>
	<xsl:template match="Hero[@id='lord_1_nikaho_6']"/>	
	<!-- SHOGUNATE -->
	<!--Ando Clan-->
	<xsl:template match="Hero[@id='lord_1_ando']"/>
	<xsl:template match="Hero[@id='lord_1_ando_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_ando_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_ando_3']"/>
	<xsl:template match="Hero[@id='lord_1_ando_4']"/>
	<xsl:template match="Hero[@id='lord_1_ando_5']"/>
	<xsl:template match="Hero[@id='lord_1_ando_6']"/>
	<xsl:template match="Hero[@id='lord_1_ando_7']"/>
	<!--Hirosaki-han-->
	<!--Tsugara Clan-->
	<xsl:template match="Hero[@id='lord_1_oura']"/>
	<xsl:template match="Hero[@id='lord_1_oura_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_oura_2']"/>
	<xsl:template match="Hero[@id='dead_lord_1_oura_3']"/>
	<xsl:template match="Hero[@id='lord_1_tozawa_3']"/>
	<!--Kuroishi Tsugaru Clan-->
	<xsl:template match="Hero[@id='lord_1_asari']"/>
	<xsl:template match="Hero[@id='lord_1_asari_1']"/>
	<xsl:template match="Hero[@id='lord_1_asari_2']"/>
	<xsl:template match="Hero[@id='lord_1_asari_3']"/>
	<!--Sugiyama Clan-->
	<xsl:template match="Hero[@id='lord_2_kakizaki']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_1']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_2']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_3']"/>
	<!-- Yamanaka Clan -->
	<xsl:template match="Hero[@id='lord_2_kakizaki_4']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_5']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_6']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_7']"/>
	<xsl:template match="Hero[@id='lord_2_kakizaki_8']"/>
	<!--Daidouji Clan-->
	<xsl:template match="Hero[@id='lord_1_tozawa']"/>
	<xsl:template match="Hero[@id='lord_1_tozawa_1']"/>
	<xsl:template match="Hero[@id='lord_1_tozawa_2']"/>
	<!--Nanbu Faction-->
	<!--Nanbu Clan-->
	<xsl:template match="Hero[@id='lord_1_nanbu']"/>
	<xsl:template match="Hero[@id='lord_1_nanbu_1']"/>
	<xsl:template match="Hero[@id='lord_1_nanbu_2']"/>
	<xsl:template match="Hero[@id='lord_1_nanbu_3']"/>
	<xsl:template match="Hero[@id='lord_1_konohe_3']"/>
	<xsl:template match="Hero[@id='lord_1_konohe_4']"/>
	<xsl:template match="Hero[@id='lord_1_konohe_5']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_4']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_5']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_6']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_7']"/>
	<!--Shichinohe Nanbu Clan-->
	<xsl:template match="Hero[@id='lord_1_shichinohe']"/>
	<xsl:template match="Hero[@id='lord_1_shichinohe_1']"/>
	<xsl:template match="Hero[@id='lord_1_shichinohe_2']"/>
	<xsl:template match="Hero[@id='lord_1_shichinohe_3']"/>
	<!--Hachinohe Nanbu Clan-->
	<xsl:template match="Hero[@id='lord_1_hachinohe']"/>
	<xsl:template match="Hero[@id='lord_1_hachinohe_1']"/>
	<xsl:template match="Hero[@id='lord_1_hachinohe_2']"/>
	<!--Nakano Clan-->
	<xsl:template match="Hero[@id='lord_1_konohe']"/>
	<xsl:template match="Hero[@id='lord_1_konohe_1']"/>
	<xsl:template match="Hero[@id='lord_1_konohe_2']"/>
	<!--Kita Clan-->
	<xsl:template match="Hero[@id='lord_1_kita']"/>
	<xsl:template match="Hero[@id='lord_1_kita_1']"/>
	<xsl:template match="Hero[@id='lord_1_kita_2']"/>
	<xsl:template match="Hero[@id='lord_1_kita_3']"/>
	<xsl:template match="Hero[@id='lord_1_kita_4']"/>
	<xsl:template match="Hero[@id='lord_1_kita_5']"/>
	<!--Nanbu Clan-->
	<xsl:template match="Hero[@id='lord_1_shiba']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_1']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_2']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_3']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_4']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_5']"/>
	<xsl:template match="Hero[@id='lord_1_shiba_6']"/>
	<xsl:template match="Hero[@id='dead_lord_1_shiba']"/>
	<!--Mito Clan-->
	<xsl:template match="Hero[@id='lord_1_asonuma']"/>
	<xsl:template match="Hero[@id='lord_1_asonuma_1']"/>
	<xsl:template match="Hero[@id='lord_1_asonuma_2']"/>
	<xsl:template match="Hero[@id='lord_1_asonuma_3']"/>
	<xsl:template match="Hero[@id='dead_lord_1_mito']"/>
	<!--Azuma Clan-->
	<xsl:template match="Hero[@id='lord_1_namioka']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_1']"/>
	<xsl:template match="Hero[@id='dead_lord_1_namioka_2']"/>
	<xsl:template match="Hero[@id='lord_1_namioka_3']"/>
	<!--Nanbu Retainers-->
	<xsl:template match="Hero[@id='lord_1_nanbu_retainers']"/>
	<xsl:template match="Hero[@id='lord_1_nanbu_retainers_1']"/>
	<xsl:template match="Hero[@id='lord_1_nanbu_retainers_2']"/>
</xsl:stylesheet>